apiVersion: operations.kafkaops.io/v1alpha1
kind: KafkaOperation
metadata:
  name: reset-motivation-topic
spec:
  operation: ResetTopic
  clusterName: digital-ocean-cluster
  clusterNamespace: kafka-worker
  topicName: motivation
  timeoutSeconds: 30
  retentionBytes: 1
  autoConfirm: true