# This rule is not used by the project kafka-ops-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to operations.kafkaops.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafka-ops-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkaoperation-viewer-role
rules:
- apiGroups:
  - operations.kafkaops.io
  resources:
  - kafkaoperations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operations.kafkaops.io
  resources:
  - kafkaoperations/status
  verbs:
  - get
