{{- if eq .Values.namespace.create true }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "kafka-ops-operator.labels" . | nindent 4 }}
  name: {{ .Values.namespace.name | quote }}
{{- end }}
