apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kafka-ops-operator
  name: kafka-ops-operator-controller-manager
  namespace: kafka-ops-operator-system
