apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kafka-ops-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
