apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kafka-ops-operator
  name: kafka-ops-operator-kafkaoperation-admin-role
rules:
- apiGroups:
  - operations.kafkaops.io
  resources:
  - kafkaoperations
  verbs:
  - '*'
- apiGroups:
  - operations.kafkaops.io
  resources:
  - kafkaoperations/status
  verbs:
  - get
