apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kafka-ops-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-kafkaoperation-editor-role
rules:
- apiGroups:
  - operations.kafkaops.io
  resources:
  - kafkaoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operations.kafkaops.io
  resources:
  - kafkaoperations/status
  verbs:
  - get
