apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kafka-ops-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
