apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kafka-ops-operator.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    control-plane: controller-manager
