apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kafka-ops-operator
    control-plane: controller-manager
  name: kafka-ops-operator-controller-manager-metrics-service
  namespace: kafka-ops-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: kafka-ops-operator
    control-plane: controller-manager
